dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-08/run.sh |
  bash
notofocations:
  slack:
    rooms:
      secure: kGFpG3YAfOtZZ+n48ZCcI2XP7oPHzwPw1wUcq0iVrcfBgDcEXk35H9KQodh9Fv5V+1tfl3wJrQZDJdzOdVWnAPFswdMlhEZ+5417O4ZYsJwPKyBHlFIh+p4PaEO7CvxpMqxHa1cour8QXrdib1vvqAusOMGRUi49+Xw61AAIniZ+P1hLs9RjXgD0OeWt31euGKM4/fOZe7obwhUTkbDx41O8TZ9rCz/OIQbhI+n1qSsfb/rPnEpN884QUQUJ9DcXQk1hYR+CpDWuYG/2BI/97EiYkCWeICuX0jJc/1ABjCHljakGUd3c3Cs5Uzira7jT1VngKlLcWwsTRmxitvews6hiKfcmLPiaVrkbxgccqVSHXI1m/aXE7s5x4AOBB9tGwUn8U+3lkQ0ro89CBRLxqGfKGlD3AminDgrJzqWwcEnn5db0qINYi+JaetBpXcl8cW2J5nNLtVlTOGb2iwOantnQhbIMyR4o9DVhBPcTyMNe4Kab+XT+M/hy3xByXizbbPFJH+BRvGxVplMGH0e7VE4HBb//lthd+lgkk1XJlO6PGi9x/PGImGtK8sJbOfZQUFf5iDa76bc3vdt0L0dio3YCfCkQDXX5D5x6eLKdUDdWjQOM8+NAQmV7dD2uoMq4klM9HOd1Fft/DavZtfqp/HtEvEBMkU+N2Eol+F4K8R4=
