dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-08/run.sh |
  bash
dd:
  secure: spbEFOcwxguKQHkUDJIxhX2TBqD14AaFlff2xD4qenxiXCZ20RNDQtTNBSLs5WaHQP+ApOrKe9WkqnnZfaU2ELcbe9S0P5KWk8vMhBlKYpnABJnI2WFWidxGpgDeKxfiYuWZxbIQlZ57TscV6D3awJMNQRSU9pmCGkRJes3+7r7gr4EZhRdsSOjmgKx1kJdQeFl+dVDXQslhJoiHt7QfqTsUDamhmKGnn1Nu3nTJo9SHI5xPDCWJoSfK5XX6GpOT4IOp4mPa9+0lYMVDqM2El8ymwwzJus3/flQJFgPAuupiBZFZj86SVjVcQv6ZVVVAz3YcVgVk+L9hZy7Ofp90NpyQEy3ZzHRYLm/Jv5kqfRT7LKUvtd2pc5phGpMLXEAUuUA/3HuK0ZuKPLBhP+fat/vp8+eJg7T9kd8SRaBQ99a4TDEKQoXCtwvTgvEEo+4NwteXgEjw3APyPUYGE5FTRSRc4QuoknbyzFWcf2WBdzU2p7AVwvecbskqulHMwelyE9s4wa0c+YLQ+HFxCl1RacWPeakwK1PaQciVfruZAdCr4T0dUqMqOY3j3I/6jLkFqeZ2tLRVjDq59UGrGAjTW0eViLk1Fedi5uTDVzS2xSVi8+w0lN0qRUUFULl63BcsK/nvr0n0SvleHCHddq0+8fphfJxX7GgATz6bnDjlmZ0=
