---
all:                    # группа со всеми хостами
  children:             # дочерние группы
    app:                # группа app
      hosts:            # хосты в группе app
        appserver:      # хост appserver
          ansible_host: 35.206.142.99  # переменная хоста
    db:                 # группа db
      hosts:            # группа db
        dbserver:       # хост dbserver
          ansible_host: 35.210.103.241 # переменная хоста

