---
- name: Deploy App
  hosts: app
  tags: deploy-tag
  become: true
  vars:
  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: "https://github.com/express42/reddit.git"
        dest: /home/nick/reddit
        version: monolith
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/nick/reddit
  handlers:
  - name: reload puma
    systemd: name=puma state=restarted

